Saagar/itemtests
ucladevx/BruinBot-Backend pull request #34
Opened 2020-12-07 01:37 UTC by Saagar3690

Finished tests for Item. 
Added the following tests:
1. POST items/add
   - Valid request
   - Missing image
   - Missing name and/or price and/or eventId in request
2. PUT items/weight
   - valid request
   - invalid itemId
   - missing itemId and/or weight in request
3. DELETE items
   - valid request
   - missing itemId and/or eventId
   - invalid itemId
   - invalid eventId

![Screen Shot 2020-12-06 at 5 34 15 PM](https://user-images.githubusercontent.com/30224372/101300094-45081f80-37e9-11eb-8f89-0b24cc570ba2.png)

2020-12-07 03:57 UTC, dvorjackz requested changes
Seems to be your test event and test item leftover. Also, some linting errors, make sure to npm run lint and fix those

<img width="1269" alt="Screen Shot 2020-12-06 at 7 54 39 PM" src="https://user-images.githubusercontent.com/32371937/101307672-e187ed00-37fc-11eb-8324-84972b9e932d.png">

2020-12-07 03:57 UTC, dvorjackz commented on package.json
> +    "test:win": "set NODE_ENV=test && mocha test/bots.js --exit && mocha test/items.js --exit",
Add --timeout 5000's to the test:win too

2020-12-07 03:57 UTC, dvorjackz commented on test/items.js
> +					assert.notStrictEqual(res.status, 200);
I think all resource not found statuses are 404, so you could say `strictEqual(res.status, 404)` here

2020-12-07 03:57 UTC, dvorjackz commented on test/items.js
> +					assert.notStrictEqual(res.status, 200);
404

2020-12-07 03:57 UTC, dvorjackz commented on test/items.js
> +					assert.notStrictEqual(res.status, 200);
404

2020-12-07 07:15 UTC, Saagar3690 reviewed
Made the changes as requested. Reverted the previous commit and undid the git add . I had done before. Minor changes to the item tests to ensure all items and events were deleted from test database.

2020-12-09 04:23 UTC, dvorjackz commented
LGTM

2020-12-09 04:24 UTC, dvorjackz approved these changes

2020-12-09 04:26 UTC, merged