Sale stats for bot
ucladevx/BruinBot-Backend pull request #57
Opened 2021-01-23 20:38 UTC by Saagar3690

### **Changes**

- Added sale stats for bot
- Sale stats is an embedded object for each bot and the reason I chose to do a sales object instead of doing itemsSold is because we can add further attributes to the sales object like moneyMade, totalCustomers, etc. so in the future if we decided to add more sale stats it would be easier
- Modified POST bots/ to include sale stats when creating a bruin bot object
- Modified the POST bots/addItem to update sale stats only if quantity is less than 0 because that implies the item is being sold
- Modified the migrations file to include sales when creating a Bot 
- Modified the createAndSaveBot in test/routes/utils.js to include sales when creating a Bot

### **Requests**
![Screen Shot 2021-01-23 at 12 37 33 PM](https://user-images.githubusercontent.com/30224372/105613500-c7d44200-5d77-11eb-88fe-43d9f824f2b0.png)

### **Database with Sale Stats
<img width="352" alt="Screen Shot 2021-01-23 at 12 21 12 PM" src="https://user-images.githubusercontent.com/30224372/105613410-29e07780-5d77-11eb-8e71-8f1b982eb767.png">
### **Database with Sale Stats**
<img width="324" alt="Screen Shot 2021-01-23 at 12 21 25 PM" src="https://user-images.githubusercontent.com/30224372/105613407-28af4a80-5d77-11eb-9921-334b8fec8b28.png">

2021-01-23 20:38 UTC, Saagar3690 commented
Oh and this is for header stats on the frontend

2021-01-26 04:10 UTC, dvorjackz commented
https://www.loom.com/share/c9a802db603347ba8248c3f81005e557

2021-01-26 04:13 UTC, dvorjackz commented
https://www.loom.com/share/c9a802db603347ba8248c3f81005e557

2021-01-30 04:52 UTC, Saagar3690 commented
### **Changes**
Updated sales stats to be for each inventory item, but still kept sales object, so that for future purposes, we can add other statistics like moneyMade, etc.
Updated BruinBot model for this change
Updated bots/addItem for this change
Create a new mongoose migration called sales which will add the sales attribute to each inventory article on up and remove it on down

2021-02-01 10:20 UTC, dvorjackz requested changes
One quick fix, everything else looks good!

2021-02-01 10:20 UTC, dvorjackz commented on routes/bots.js
> +
Maybe let's have another endpoint for this? It's not really clear that an endpoint called "addItem" will be used to signal an item being sold.

2021-02-03 03:05 UTC, Saagar3690 commented
### **Changes**
Reset the addItem endpoint
Created a new endpoint: PUT bots/purchase, which updates inventory and keeps track of sale stats

### **Screenshots**
![Screen Shot 2021-02-02 at 7 04 36 PM](https://user-images.githubusercontent.com/30224372/106692585-9df5f900-6589-11eb-8c84-5be8dcde840d.png)
![Screen Shot 2021-02-02 at 7 04 18 PM](https://user-images.githubusercontent.com/30224372/106692590-9e8e8f80-6589-11eb-87ab-762842f0f321.png)

2021-02-03 08:23 UTC, dvorjackz approved these changes
LGTM!

2021-02-03 08:23 UTC, merged